//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMeFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class companyLogo
    {
        public int companyLogoID { get; set; }
        public int companyID { get; set; }
        public string companyImage { get; set; }
    
        public virtual company company { get; set; }
    }
}
