//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMeFinal.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class HireMeEntities : DbContext
    {
        public HireMeEntities()
            : base("name=HireMeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<businessIndustry> businessIndustries { get; set; }
        public virtual DbSet<company> companies { get; set; }
        public virtual DbSet<companyIndustry> companyIndustries { get; set; }
        public virtual DbSet<companyLogo> companyLogoes { get; set; }
        public virtual DbSet<educationDetail> educationDetails { get; set; }
        public virtual DbSet<jobApplicationStatu> jobApplicationStatus { get; set; }
        public virtual DbSet<jobLocation> jobLocations { get; set; }
        public virtual DbSet<jobPostAction> jobPostActions { get; set; }
        public virtual DbSet<jobPostActivity> jobPostActivities { get; set; }
        public virtual DbSet<jobPostActivityLog> jobPostActivityLogs { get; set; }
        public virtual DbSet<jobPosting> jobPostings { get; set; }
        public virtual DbSet<jobPostSkillSet> jobPostSkillSets { get; set; }
        public virtual DbSet<jobType> jobTypes { get; set; }
        public virtual DbSet<skillSet> skillSets { get; set; }
        public virtual DbSet<studentExperience> studentExperiences { get; set; }
        public virtual DbSet<studentProfile> studentProfiles { get; set; }
        public virtual DbSet<studentSkillSet> studentSkillSets { get; set; }
        public virtual DbSet<userAccount> userAccounts { get; set; }
        public virtual DbSet<userLog> userLogs { get; set; }
        public virtual DbSet<userType> userTypes { get; set; }
    }
}
