//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMeFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class jobPostSkillSet
    {
        [Key]
        public int skillSetID { get; set; }
        public int jobPostingID { get; set; }
        public int skillLevel { get; set; }
    
        public virtual jobPosting jobPosting { get; set; }
        public virtual skillSet skillSet { get; set; }
    }
}
