//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMeFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobPosting
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jobPosting()
        {
            this.jobPostActivities = new HashSet<jobPostActivity>();
            this.jobPostSkillSets = new HashSet<jobPostSkillSet>();
        }
    
        public int jobPostingID { get; set; }
        public int jobTypeID { get; set; }
        public int companyID { get; set; }
        public int jobLocationID { get; set; }
        public int userAccountID { get; set; }
        public int jobCategoryID { get; set; }
        public int applicantTypeID { get; set; }
        public System.DateTime createdDate { get; set; }
        public string jobDescription { get; set; }
        public string jobTitle { get; set; }
        public int numOpenings { get; set; }
        public int hoursPerWeek { get; set; }
        public decimal wageSalary { get; set; }
        public System.DateTime startDate { get; set; }
        public System.DateTime endDate { get; set; }
        public string qualifications { get; set; }
        public string applicationInstructions { get; set; }
        public string applicationWebsite { get; set; }
        public System.DateTime postingDate { get; set; }
        public System.DateTime expirationDate { get; set; }
        public bool enabled { get; set; }
        public int numViews { get; set; }
    
        public virtual company company { get; set; }
        public virtual jobLocation jobLocation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobPostActivity> jobPostActivities { get; set; }
        public virtual jobType jobType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobPostSkillSet> jobPostSkillSets { get; set; }
        public virtual userAccount userAccount { get; set; }
    }
}
