//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMeFinal.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobPostActivityLog
    {
        public int jobPostActivityLogID { get; set; }
        public int jobPostActivityID { get; set; }
        public int jobPostActionID { get; set; }
        public System.DateTime actionDate { get; set; }
        public int userAccountID { get; set; }
    
        public virtual jobPostAction jobPostAction { get; set; }
        public virtual jobPostActivity jobPostActivity { get; set; }
    }
}
