//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HireMeFinal.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class userLog
    {
        [Key]
        public int userAccountID { get; set; }
        public System.DateTime lastLoginDate { get; set; }
        public Nullable<System.DateTime> lastApplyDate { get; set; }
    
        public virtual userAccount userAccount { get; set; }
    }
}
